server:
  port: 8080
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path: /tiros
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-origins: '*'
        allowed-headers: '*'
        allowed-methods: '*'
        allow-credentials: true
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      enabled: true

spring:
  application:
    name: tiros_manage
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    user:
      name: tiros
      password: tiros_actuator
#  boot:
#    admin:
#      client:
#        url: http://localhost:9999
#        username: admin
#        password: admin
#        instance:
#          name: 业务服务
#          service-url: http://localhost:${server.port}/tiros
#          metadata:
#            user.name: ${spring.security.user.name}
#            user.password: ${spring.security.user.password}
  mail:
    host: smtp.163.com
    username: jeecgos@163.com
    password: ??
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  ## quartz定时任务,采用数据库方式
  quartz:
    job-store-type: jdbc
    initialize-schema: embedded
    #设置自动启动，默认为 true
    auto-startup: true
    #启动时更新己存在的Job
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            misfireThreshold: 60000
            clusterCheckinInterval: 10000
            acquireTriggersWithinLock: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  #json 时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    open-in-view: false
  aop:
    proxy-target-class: true
  #配置freemarker
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    prefer-file-system-access: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 1000
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      primary: oracle #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        #        mysql:
        #          username: root
        #          password: root
        #          url: jdbc:mysql://localhost:3306/tiros_dev?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
        #          driver-class-name: com.mysql.jdbc.Driver
        oracle:
          #          # 轨道交通正式环境
          #          url: jdbc:oracle:thin:@//10.97.4.6:1521/tiros
          #          username: tiros
          #          password: tiros#20240308
          #          driver-class-name: oracle.jdbc.driver.OracleDriver
          #          # 轨道交通测试环境
          #          url: jdbc:oracle:thin:@//10.98.14.12:1521/tirostest
          #          username: tiros_test
          #          password: tirostest#123
          #          driver-class-name: oracle.jdbc.driver.OracleDriver
          # 轨道交通测试环境-信息部
          url: jdbc:oracle:thin:@//10.98.14.47:1521/ORCL
          username: tiros
          password: admin#123
          driver-class-name: oracle.jdbc.driver.OracleDriver
          #          # 公司开发环境（外网）
          #          url: jdbc:oracle:thin:@//159.75.51.109:1521/orcl
          #          username: tiros_dev
          #          password: 123456
          #          driver-class-name: oracle.jdbc.driver.OracleDriver
          #          # 公司开发环境（内网）
          #          url: jdbc:oracle:thin:@//192.168.31.10:1521/orcl
          #          username: tiros_dev
          #          password: 123456
          #          driver-class-name: oracle.jdbc.driver.OracleDriver
          #          # 本机开发环境
          #          url: jdbc:oracle:thin:@//localhost:1521/tiros
          #          username: tiros
          #          password: 123456
          #          driver-class-name: oracle.jdbc.driver.OracleDriver
  #redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password:
    port: 6379
#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:org/jeecg/**/mapper/xml/${spring.datasource.dynamic.primary}/*Mapper.xml,classpath*:/mapper/${spring.datasource.dynamic.primary}/**/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: UUID
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null' # 针对所有的空字段都进行空处理, 如果有些字段空值默认值需要传入0或者其他时，可以采用字段注解方式 @TableField(el = " 字段名, jdbcType=字段类型 ")
#jeecg专用配置
jeecg:
  # 本地：local\Minio：minio\阿里云：alioss
  uploadType: local
  path:
    #文件上传根目录 设置
    upload: /opt/jeecg-boot/upload
    #webapp文件路径
    webapp: /opt/jeecg-boot/webapp
  #短信秘钥
  sms:
    accessKeyId: LTAIpW4gUG7xYDNI
    accessKeySecret: ??
  shiro:
    excludeUrls: /sso/**,/ssoclient/**,/oauth2/**
  #阿里云oss存储配置
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKey: ??
    secretKey: ??
    bucketName: jeecgos
    staticDomain: https://static.jeecg.com
  # ElasticSearch 设置
  elasticsearch:
    cluster-name: jeecg-ES
    cluster-nodes: 127.0.0.1:9200
    check-enabled: true
  # 表单设计器配置
  desform:
    # 主题颜色（仅支持 16进制颜色代码）
    theme-color: "#1890ff"
  # 在线预览文件服务器地址配置
  file-view-domain: http://fileview.jeecg.com
  # minio文件上传
  minio:
    minio_url: http://minio.jeecg.com
    minio_name: ??
    minio_pass: ??
    bucketName: otatest
  captcha:
    enable: false
#cas单点登录
cas:
  prefixUrl: http://cas.example.org:8443/cas
logging:
  file: logs/${spring.application.name}.log
  level:
    org.jeecg.modules.system.aspect: info
    org.jeecg.modules.system.mapper: debug
#enable swagger
swagger:
  enable: true
#业务相关配置
tiros:
  base:
    # 存放架大修车间库房信息的上级节点
    rootWarehouse: '2'
    #默认库存组织
    defaultSysHouseCategory: AJ1
  #工作流地址路径
  wf:
    address: http://localhost:9096
    path:
      startSolution: /process/instance/start/solution
      listCurrentTask: /process/instance/queryCandidate
      signal: /process/instance/signal
      completeTask: /process/task/complete
      stopProcess: /process/task/stopProcess
      taskData: /process/task/getTaskData
      suspendInstance: /process/instance/suspend
      activateInstance: /process/instance/activate
      deleteInstance: /process/instance/delete
  #UUV同步地址
#  sync:
#    account: JDXAdmin
#    password: 111111
#    address: http://esb.sz-mtr.com/BizTalkESB/UpdateUUV.asmx
  sync:
    account: JDXAdmin
    password: jdx@2023
    address: http://apisix.sz-mtr.com:9080/apigw/platform_zNgV39Ec/Services/UUVGet.asmx
  #maximo服务地址路径
  maximo:
    address: http://localhost:8090
    path:
      readMaterialStockChange: /third/maximo/read/trans/change-stock
      readMaterialReWrite: /third/maximo/read/trans/rewrite-consume
  #数据隔离配置
  dataIsolation:
    #数据库方言
    dialect: ${spring.datasource.dynamic.primary}
    #需要数据隔离的表
    tableNames: bu_mtr_line,bu_mtr_track,bu_mtr_workstation,bu_base_alert,bu_train_info,bu_train_structure,bu_repair_tech_book,bu_repair_regu_info,bu_tp_repair_plan,bu_base_form_template,bu_work_check,bu_repair_plan_far,bu_repair_plan_year,bu_repair_plan,bu_base_train_repair_period,bu_repair_exchang,bu_work_order,bu_work_leave_record,bu_work_rectify,bu_fault_info,bu_outsource_outin,bu_base_supplier,bu_contract_info,bu_rpt_board_sys_fault,bu_rpt_board_sys_material,bu_rpt_board_train_fault,bu_rpt_board_train_material,bu_rpt_excel_template,bu_rpt_person_kpi,bu_rpt_plan_group_statistic,bu_rpt_day_report,bu_mtr_warehouse,bu_material_apply,bu_material_borrow,bu_material_entry_order,bu_material_must_list,bu_material_pallet,bu_material_qrcode,bu_material_returned,bu_material_stock,bu_material_group_stock,bu_material_tools,bu_material_turnover,bu_material_year_plan,bu_spec_assets,bu_doc_directory,bu_doc_directory_group,bu_doc_directory_person,bu_doc_file,bu_training,bu_training_record,bu_material_turnover,bu_material_spare_part,bu_mtr_workshop_group,bu_material_stock_use
    #tableNames: bu_work_order
    #数据隔离字段：workshop_id,line_id,company_id
    isolationColumns: workshop_id
    #忽略筛选数据库中隔离字段的值为空的数据，默认true隔离字段的值为空的数据都能查询到
    ignoreDbNullData: true

oauth2:
  server: http://10.97.10.5:8080/sso            # sso 服务地址
  webAddress: http://localhost:3000             # WEB前端地址
  provider:
    authorization-uri: ${oauth2.server}/oauth2/authorize          # 授权url固定值
    token-uri: ${oauth2.server}/oauth2/token                      # 获取令牌url，固定值
    user-info-uri: ${oauth2.server}/oauth2/userinfo               # 获取用户信息url，固定值
    userNameAttribute: username                                   # 用户信息中获取用户名的属性，固定值
    jwk-set-uri: ${oauth2.server}/oauth2/token_keys               # 获取加密公钥url，固定值
    logout-uri: ${oauth2.server}/oauth2/logout
  registration:
    client-id: a9efd36c-37fb-11ed-aba9-0050569770b5               # 客户端账号，默认值clientId，定制值需在sso中申请
    client-secret: a9efd3b8-37fb-11ed-aba9-0050569770b5           # 客户端密钥，默认值clientSecret，定制值需在sso中申请
    authorization-grant-type: authorization_code                  # 固定值
    redirect-uri: 'http://localhost:8080/tiros/oauth2/login/callback'           # spring官网文档提供的配置示例，用于登录后返回的地址
    logout-notice-uri: 'http://localhost:8080/tiros/oauth2/logout/notice'       # 当sso注销时回调地址
    logout-redirect-uri: ${oauth2.webAddress}                                   # 当本地调用sso注销接口后跳转的地址
